import express from "express";
import multer from "multer";
import { GoogleGenerativeAI } from "@google/generative-ai";
import dotenv from "dotenv";
import cors from "cors";
import path from "path";
import { fileURLToPath } from "url";
import fs from "fs";

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const port = process.env.PORT || 5050;

// Setup Gemini API
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash-lite" });

app.use(cors());
app.use(express.json({ limit: "50mb" }));
app.use(express.urlencoded({ limit: "50mb", extended: true }));
app.use(express.static("public"));

// Configure Multer for PDF uploads
const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    const uploadDir = "uploads";
    if (!fs.existsSync(uploadDir)) {
      fs.mkdirSync(uploadDir);
    }
    cb(null, uploadDir);
  },
  filename: (req, file, cb) => {
    cb(null, `${Date.now()}-${file.originalname}`);
  },
});

const upload = multer({
  storage,
  fileFilter: (req, file, cb) => {
    if (file.mimetype === "application/pdf") {
      cb(null, true);
    } else {
      cb(new Error("Only PDF files are allowed!"), false);
    }
  },
  limits: { fileSize: 20 * 1024 * 1024 }, // 20MB limit
});

// Helper function to convert file to GoogleGenerativeAI.Part
function fileToGenerativePart(path, mimeType) {
  return {
    inlineData: {
      data: Buffer.from(fs.readFileSync(path)).toString("base64"),
      mimeType,
    },
  };
}

// Custom upload handler to catch Multer errors (like file size limits)
const uploadMiddleware = upload.single("pdf");

app.post("/upload", (req, res, next) => {
  uploadMiddleware(req, res, (err) => {
    if (err instanceof multer.MulterError) {
      // A Multer error occurred when uploading (e.g., file too large)
      return res.status(400).json({ error: `Upload error: ${err.message}` });
    } else if (err) {
      // An unknown error occurred when uploading
      return res.status(400).json({ error: err.message });
    }
    // Everything went fine, proceed to the next handler
    next();
  });
}, async (req, res) => {
  try {
    const mode = req.body.mode || "pdf_prompt"; // default mode
    let prompt = "";
    let generativeParts = [];

    if (mode === "prompt_only") {
      prompt = req.body.prompt;
      if (!prompt) {
        return res.status(400).json({ error: "Prompt is required for Prompt Only mode" });
      }
    } else if (mode === "pdf_prompt") {
      if (!req.file) {
        return res.status(400).json({ error: "PDF file is required for PDF + Prompt mode" });
      }
      prompt = req.body.prompt || "Please summarize this PDF file.";
      generativeParts.push(fileToGenerativePart(req.file.path, "application/pdf"));
    } else if (mode === "pdf_only") {
      if (!req.file) {
        return res.status(400).json({ error: "PDF file is required for PDF Only mode" });
      }
      prompt = "Please summarize this PDF file.";
      generativeParts.push(fileToGenerativePart(req.file.path, "application/pdf"));
    } else {
      return res.status(400).json({ error: "Invalid mode" });
    }

    const result = await model.generateContent([prompt, ...generativeParts]);
    const response = await result.response;
    const text = response.text();

    // Extract token usage metadata
    const usage = response.usageMetadata;

    // Clean up uploaded file if it exists
    if (req.file && fs.existsSync(req.file.path)) {
      fs.unlinkSync(req.file.path);
    }

    res.json({
      text,
      usage: {
        promptTokenCount: usage.promptTokenCount,
        candidatesTokenCount: usage.candidatesTokenCount,
        totalTokenCount: usage.totalTokenCount,
        explanation: {
          promptTokenCount:
            "Input tokens: These are the tokens in your prompt and any uploaded content. Gemini processes these to understand your request.",
          candidatesTokenCount:
            "Output tokens: These are the tokens generated by Gemini in its response.",
          totalTokenCount:
            "Total tokens: The sum of input and output tokens, representing the total computational cost of the request.",
        },
      },
    });
  } catch (error) {
    console.error("Error processing request:", error);
    if (req.file && fs.existsSync(req.file.path)) {
      fs.unlinkSync(req.file.path);
    }
    res.status(500).json({ error: `AI Processing Error: ${error.message}` });
  }
});

// Global error handler to catch any other unhandled errors and return JSON
app.use((err, req, res, next) => {
  console.error("Global error handler:", err);
  res.status(err.status || 500).json({
    error: err.message || "An unexpected server error occurred"
  });
});

app.listen(port, () => {
  console.log(`Server running at http://localhost:${port}`);
});
